// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package get_connection_url

import (
	appconfig "vpn/internal/config"
	"vpn/internal/hysteria/infra/configrepo"
)

func BuildUseCase(cfg appconfig.Config) (*UseCase, error) {
	string2 := provideConfigPath(cfg)
	repository := configrepo.NewRepository(string2)
	useCase := NewUseCase(repository)
	return useCase, nil
}
