// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package get_user_stats

import (
	appconfig "vpn/internal/config"
	"vpn/internal/hysteria/infra/trafficstats"
)

func BuildUseCase(cfg appconfig.Config) (*UseCase, error) {
	bool2 := provideTrafficStatsEnabled(cfg)
	string2 := provideTrafficStatsURL(cfg)
	string3 := provideTrafficStatsSecret(cfg)
	duration := provideTrafficStatsTimeout(cfg)
	client := trafficstats.NewClient(bool2, string2, string3, duration)
	useCase := NewUseCase(client)
	return useCase, nil
}
