// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package add_user

import (
	appconfig "vpn/internal/config"
	"vpn/internal/hysteria/infra/configrepo"
	"vpn/internal/hysteria/infra/servicectl"
	utilpasswordgen "vpn/internal/utils/passwordgen"
)

func BuildUseCase(cfg appconfig.Config) (*UseCase, error) {
	string2 := provideConfigPath(cfg)
	repository := configrepo.NewRepository(string2)
	bool2 := provideRestartEnabled(cfg)
	string3 := provideServiceName(cfg)
	string4 := provideRestartCommand(cfg)
	restarter := servicectl.NewRestarter(bool2, string3, string4)
	generator := utilpasswordgen.NewGenerator()
	useCase := NewUseCase(repository, restarter, generator)
	return useCase, nil
}
